### ISSUE TITLE
[Feat]: 큐레이션 페이지 구현

### ISSUE THREAD

**Issue by Cho-yunah** [soolsul/soolsul-client#26]
## Description
큐레이션 페이지 UI 구현

## TODO
- [x] 큐레이션 목록 화면 구현
- [x] 상세 페이지 화면 구현 
- [x] 상세 페이지의 정보 및 리뷰 탭 구현
