### ISSUE TITLE
[Feat]: 큐레이션 api 연결

### ISSUE THREAD

**Issue by Cho-yunah** [soolsul/soolsul-client#35]
## Description
큐레이션 api 연결

## TODO
- [ ] 큐레이션 목록 페이지 api 연결
- [ ] 큐레이션 목록 조회시 브라우저에 보이는 url 조정
- [ ] 상세 페이지 api 연결

## Linked Issue
"#이슈번호"
